version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: development
    ignore:
      - dependency-name: orchestra/testbench
    groups:
      composer:
        update-types: [minor, patch]
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
