name: Static analysis

on:
  pull_request:
  push:
    branches-ignore: [master]

jobs:
  static-analysis:
    name: PHP ${{ matrix.php }}, L ${{ matrix.laravel }}, ${{ matrix.stability }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '8.1'
            laravel: '10.*'
            stability: prefer-lowest
          - php: '8.2'
            laravel: '10.*'
            stability: prefer-stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Get Composer cache directory path
        id: composer-cache-dir
        run: echo "::set-output name=path::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache-dir.outputs.path }}
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer update laravel/framework:${{ matrix.laravel }} orchestra/testbench --with-all-dependencies --${{ matrix.stability }}

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze --no-progress --no-interaction
