name: Tests

on: [push]

jobs:
  unit-tests:
    name: PHP ${{ matrix.php }}, ${{ matrix.stability }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']
        stability: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} ${{ matrix.flags }} --prefer-dist --no-progress --no-interaction

      - name: Execute tests
        run: vendor/bin/pest

  static-analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-progress --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress --no-interaction
